{{- if .Values.outscale.credentials.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nums3-console.fullname" . }}-outscale
  labels:
    {{- include "nums3-console.labels" . | nindent 4 }}
type: Opaque
stringData:
  accessKey: {{ .Values.outscale.credentials.accessKey | quote }}
  secretKey: {{ .Values.outscale.credentials.secretKey | quote }}
  region: {{ .Values.outscale.credentials.region | quote }}
{{- end }}
